### ISSUE TITLE
Make links clickable in view-change

### ISSUE THREAD

**Issue by mbovel** [herselamkahsay/testing-and-learning#1]
Nice works with the buttons!

Now, what I would like is to make the links clickable so that you can view an individual product by clicking on its name, and come back the home page by clicking on `Go back to home page`.

In order to that, you can add click handlers in the same way that you did for your buttons. In addition, you will need to set the `href` attributes of links to `#` (this way, they become blue and clickable). You will also need to use [`e.preventDefault()`](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) in the click handlers.

Current flow:

![Powercoders images-1](https://user-images.githubusercontent.com/777748/121805141-1c565c00-cc4a-11eb-8f63-28e0006dae86.jpg)

What I would like:

![Powercoders images](https://user-images.githubusercontent.com/777748/121805142-224c3d00-cc4a-11eb-8d30-d9f68ca0192d.jpg)

**Comment by herselamkahsay** [comment]
Hi Mattieu,
Okay, I will make it. Thank you for the message. Have a great Sunday!
